namespace Auralis;

internal readonly record struct TaskbarWidgetBounds(int Left, int Top, int Right, int Bottom);

/// <summary>
/// Suppresses duplicate visibility and native placement work generated by the player's frequent
/// playback heartbeat. It deliberately contains no WPF or Win32 dependencies so the policy can be
/// regression-tested without touching Explorer.
/// </summary>
internal sealed class TaskbarWidgetUpdateGate
{
    private const int BoundsTolerancePixels = 2;
    private bool _enabled;
    private bool _hasAppliedBounds;
    private TaskbarWidgetBounds _appliedBounds;

    internal bool TryChangeEnabled(bool enabled)
    {
        if (_enabled == enabled)
        {
            return false;
        }

        _enabled = enabled;
        return true;
    }

    internal bool ShouldApplyBounds(TaskbarWidgetBounds bounds, bool isNativeVisible)
    {
        return !isNativeVisible || !_hasAppliedBounds || !AreClose(bounds, _appliedBounds);
    }

    internal void MarkBoundsApplied(TaskbarWidgetBounds bounds)
    {
        _appliedBounds = bounds;
        _hasAppliedBounds = true;
    }

    internal void ResetBounds()
    {
        _hasAppliedBounds = false;
        _appliedBounds = default;
    }

    private static bool AreClose(TaskbarWidgetBounds left, TaskbarWidgetBounds right)
    {
        return Math.Abs(left.Left - right.Left) <= BoundsTolerancePixels &&
               Math.Abs(left.Top - right.Top) <= BoundsTolerancePixels &&
               Math.Abs(left.Right - right.Right) <= BoundsTolerancePixels &&
               Math.Abs(left.Bottom - right.Bottom) <= BoundsTolerancePixels;
    }
}

internal static class TaskbarWidgetRecoveryBackoff
{
    private static readonly TimeSpan[] Delays =
    [
        TimeSpan.FromSeconds(5),
        TimeSpan.FromSeconds(10),
        TimeSpan.FromSeconds(20),
        TimeSpan.FromSeconds(40),
        TimeSpan.FromSeconds(60)
    ];

    internal static TimeSpan GetDelay(int consecutiveFailureCount)
    {
        var index = Math.Clamp(consecutiveFailureCount, 0, Delays.Length - 1);
        return Delays[index];
    }
}
